"use client";
import { Layout, theme } from "antd";
import { Geist, Geist_Mono } from "next/font/google";
import "../page.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const { Content, Footer } = Layout;

export default function authLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const {
    token: { colorBgContainer, borderRadiusLG },
  } = theme.useToken();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Layout style={{ minHeight: "100vh" }}>
          <Content style={{ padding: "48px 24px" }}>
            <div
              style={{
                padding: 24,
                minHeight: 380,
                maxWidth: 1200,
                margin: "0 auto",
                background: colorBgContainer,
                borderRadius: borderRadiusLG,
              }}
            >
              {children}
            </div>
          </Content>
          <Footer style={{ textAlign: "center" }}>
            Gym App ©{new Date().getFullYear()}
          </Footer>
        </Layout>
      </body>
    </html>
  );
}


// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import  "../page.module.css";
// import { Layout, theme } from "antd";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
// const { Content, Footer } = Layout;

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function authLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         <Layout style={{ minHeight: "100vh" }}>
//           <Content style={{ padding: "48px 24px" }}>
//           <div
//            style={{
//             padding: 24,
//             minHeight: 380,
//             maxWidth: 1200,
//             margin: '0 auto',
//             background: "#f5f5f5",
//             borderRadius: "8px",
//           }}>
//             {children}
//           </div>
//           </Content>
//           <Footer style={{textAlign:"center"}}>
//             Gym App @{new Date().getFullYear()}
//           </Footer>
//         </Layout>
//       </body>
//     </html>
//   );
// }
